# Generated by Django 4.2.4 on 2023-10-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancerprofilemodel",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
