# Generated by Django 4.2.4 on 2023-10-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_freelancerprofilemodel_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
                ("skill", models.CharField(max_length=200)),
                ("interest", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="freelancer/")),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.freelencer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FreelancerProfileModel",
        ),
    ]
