# Generated by Django 4.2.4 on 2023-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clientprofile_approveproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="approveproject",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
